export default {
  defaultTheme: 'dark',
  themes: {
    'light': {
      colors: {
        'background': '#efedf0',
        'surface': '#faf9fc',
        'surface-dim': '#dbd9dd',
        'surface-bright': '#faf9fc',
        'on-surface': '#1b1c1e',
        'outline': '#75777f',
        'outline-variant': '#c5c6cf',
        'primary': '#4a5e89',
        'on-primary': '#ffffff',
        'secondary': '#326381',
        'on-secondary': '#ffffff',
        'tertiary': '#625887',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'surface-light': '#e9e7eb',
      },
      dark: false,
      variables: {
        'overlay-background': '#191c22',
      },
    },
    'light-high-contrast': {
      colors: {
        'background': '#e3e2e5',
        'surface': '#faf9fc',
        'surface-dim': '#b9b8bb',
        'surface-bright': '#faf9fc',
        'on-surface': '#000000',
        'outline': '#292c33',
        'outline-variant': '#474950',
        'primary': '#162b53',
        'on-primary': '#ffffff',
        'secondary': '#003046',
        'on-secondary': '#ffffff',
        'tertiary': '#2f2551',
        'on-tertiary': '#ffffff',
        'error': '#600004',
        'on-error': '#ffffff',
        'surface-light': '#e9e7eb',
      },
      dark: false,
      variables: {
        'overlay-background': '#191c22',
      },
    },
    'dark': {
      colors: {
        'background': '#1f2022',
        'surface': '#121316',
        'surface-dim': '#121316',
        'surface-bright': '#38393c',
        'on-surface': '#e3e2e5',
        'outline': '#8f9099',
        'outline-variant': '#44474e',
        'primary': '#2c4069',
        'on-primary': '#d8e2ff',
        'secondary': '#9cccef',
        'on-secondary': '#00344c',
        'tertiary': '#ccbff5',
        'on-tertiary': '#332955',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'surface-light': '#38393c',
      },
      dark: true,
      variables: {
        'overlay-background': '#191c22',
      },
    },
  },
}
